### ISSUE TITLE
EthStaker round: Arbitrum balances not showing in Profile.vue

### ISSUE THREAD

**Issue by samajammin** [clrfund/monorepo#471]
Noticed an error in the profile component:
![Image 2022-03-03 at 12 31 53 PM](https://user-images.githubusercontent.com/8097623/156648477-5d05fe23-1cc1-434e-8b88-7fe60ba6d476.jpg)

I suspect this is supposed to show DAI balance on Arbitrum?

Browser console error:
```
chunk-vendors.fa3a781c.js:135 Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.4.1)
    at h.makeError (chunk-vendors.fa3a781c.js:135:264458)
    at h.throwError (chunk-vendors.fa3a781c.js:135:264578)
    at h.throwArgumentError (chunk-vendors.fa3a781c.js:135:264633)
    at Function.from (chunk-vendors.fa3a781c.js:129:158924)
    at d (chunk-vendors.fa3a781c.js:13:7300)
    at u (chunk-vendors.fa3a781c.js:47:29602)
    at $e (app.979eb883.js:1:102156)
    at a.get (app.979eb883.js:1:144488)
    at nr.get (chunk-vendors.fa3a781c.js:135:30684)
    at nr.evaluate (chunk-vendors.fa3a781c.js:135:31685)
```

**Comment by samajammin** [comment]
@pettinarip mind taking a look?

**Comment by samajammin** [comment]
Checked again & it appears to be working now 🤔 
![Image 2022-03-08 at 5 41 34 PM](https://user-images.githubusercontent.com/8097623/157355762-bdb4ce8b-0746-4750-87c0-706aefa5cd55.jpg)

I'll close this out for now - please re-open if anyone is able to reproduce!
